### ISSUE TITLE
NoClassDefFoundError after updating from 2.9.1 to 2.9.2

### ISSUE THREAD

**Issue by PedroBarbosaPT** [java-native/jssc#70]
Hi
After updating from 2.9.1 to 2.9.2 this exception showed up:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/scijava/nativelib/NativeLoader
	at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:88)
	at jssc.SerialPortList.<clinit>(SerialPortList.java:43)
	at main(Main.java:38)
Caused by: java.lang.ClassNotFoundException: org.scijava.nativelib.NativeLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

```
Note: I'm adding .jar manually without Maven

**Comment by tresf** [comment]
@JockX do you recall where we got the [release jar](https://github.com/java-native/jssc/releases/tag/v2.9.2) from?  I have a feeling we skipped a step, perhaps `jar-with-dependencies`.

I'll re-run this locally and see if it fixes @PedroBarbosaPT's issue.

**Comment by tresf** [comment]
@PedroBarbosaPT can you see if this JAR fixes your issue?  If so, I'll update the artifact in the releases area so others don't suffer this same problem.

[jssc-2.9.2.jar.zip](https://github.com/java-native/jssc/files/5063484/jssc-2.9.2.jar.zip)

**Comment by PedroBarbosaPT** [comment]
It's working perfectly now, thanks

**Comment by PedroBarbosaPT** [comment]
It's working perfectly now, thanks

**Comment by tresf** [comment]
@PedroBarbosaPT thanks for the quick turnaround.  Updated artifact at https://github.com/java-native/jssc/releases/tag/v2.9.2.
